// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransparencyPortal.Api.Data;

#nullable disable

namespace TransparencyPortal.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405035842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TransparencyPortal.Api.Models.DefaultQuestion", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_default_questions");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_default_questions_slug");

                    b.ToTable("default_questions", (string)null);
                });

            modelBuilder.Entity("TransparencyPortal.Api.Models.Inquiry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomQuestionText")
                        .HasColumnType("longtext")
                        .HasColumnName("custom_question_text");

                    b.Property<ulong?>("DefaultQuestionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("default_question_id");

                    b.Property<string>("ElaborationText")
                        .HasColumnType("longtext")
                        .HasColumnName("elaboration_text");

                    b.Property<DateTime?>("FirstResponseAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_response_at");

                    b.Property<string>("PathType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("path_type");

                    b.Property<ulong?>("PresetResponseId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("preset_response_id");

                    b.HasKey("Id")
                        .HasName("pk_inquiries");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_inquiries_created_at");

                    b.HasIndex("DefaultQuestionId")
                        .HasDatabaseName("ix_inquiries_default_question_id");

                    b.HasIndex("PathType")
                        .HasDatabaseName("ix_inquiries_path_type");

                    b.HasIndex("PresetResponseId")
                        .HasDatabaseName("ix_inquiries_preset_response_id");

                    b.ToTable("inquiries", (string)null);
                });

            modelBuilder.Entity("TransparencyPortal.Api.Models.PresetResponse", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body_text");

                    b.Property<ulong>("DefaultQuestionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("default_question_id");

                    b.Property<DateTime>("PublishedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_preset_responses");

                    b.HasIndex("DefaultQuestionId")
                        .HasDatabaseName("ix_preset_responses_default_question_id");

                    b.ToTable("preset_responses", (string)null);
                });

            modelBuilder.Entity("TransparencyPortal.Api.Models.Inquiry", b =>
                {
                    b.HasOne("TransparencyPortal.Api.Models.DefaultQuestion", "DefaultQuestion")
                        .WithMany("Inquiries")
                        .HasForeignKey("DefaultQuestionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inquiries_default_questions_default_question_id");

                    b.HasOne("TransparencyPortal.Api.Models.PresetResponse", "PresetResponse")
                        .WithMany("Inquiries")
                        .HasForeignKey("PresetResponseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inquiries_preset_responses_preset_response_id");

                    b.Navigation("DefaultQuestion");

                    b.Navigation("PresetResponse");
                });

            modelBuilder.Entity("TransparencyPortal.Api.Models.PresetResponse", b =>
                {
                    b.HasOne("TransparencyPortal.Api.Models.DefaultQuestion", "DefaultQuestion")
                        .WithMany("PresetResponses")
                        .HasForeignKey("DefaultQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_preset_responses_default_questions_default_question_id");

                    b.Navigation("DefaultQuestion");
                });

            modelBuilder.Entity("TransparencyPortal.Api.Models.DefaultQuestion", b =>
                {
                    b.Navigation("Inquiries");

                    b.Navigation("PresetResponses");
                });

            modelBuilder.Entity("TransparencyPortal.Api.Models.PresetResponse", b =>
                {
                    b.Navigation("Inquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
